FROM golang:1.21

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go install github.com/cosmtrek/air@latest
RUN go env -w GOFLAGS="-buildvcs=false"

EXPOSE 3001
EXPOSE 27017

CMD ["air"]
